const LONG_TEXT = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras et viverra arcu. Nam finibus nisi id lectus tempus semper. Curabitur tellus turpis, feugiat vel maximus id, pellentesque ac elit. Curabitur hendrerit vehicula sem a posuere. Integer egestas, velit nec consequat hendrerit, urna ante sodales erat, commodo aliquam ligula diam et neque. Nunc ut velit cursus, porta metus sit amet, interdum ipsum. Maecenas congue tortor diam, vitae aliquam elit faucibus at. Cras non pretium nibh, eu molestie nisl. Nulla et placerat purus, sit amet molestie neque. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Integer ullamcorper enim eget enim tristique, id tristique orci faucibus. Curabitur neque massa, ultricies quis neque eget, bibendum lobortis lectus.\n" +
    "\n" +
    "Vestibulum aliquet ipsum non blandit mattis. Curabitur commodo tincidunt risus, sit amet vehicula enim tincidunt a. Praesent facilisis turpis lectus, non consectetur ipsum consectetur dapibus. Aliquam ac ultricies purus. Nam malesuada cursus nibh, quis posuere metus cursus id. Integer dolor eros, euismod non nisi eget, congue pharetra mi. Aliquam convallis elit dolor, in scelerisque purus feugiat sit amet. Fusce euismod, enim at dignissim mollis, ipsum eros tincidunt tortor, ut condimentum turpis magna vitae sem. Etiam faucibus leo rutrum ligula varius efficitur. Etiam rhoncus nunc a arcu cursus malesuada. Curabitur aliquam lacus quis pulvinar dapibus. Maecenas tempus neque nec dolor tristique iaculis.\n" +
    "\n" +
    "Suspendisse vehicula nisi id elementum aliquam. Donec aliquet eros eu accumsan commodo. Nunc a maximus eros. Nulla nec viverra tellus, dignissim laoreet ligula. Nunc pellentesque pulvinar nisi, ac sagittis eros sollicitudin nec. Nunc mollis, elit id suscipit laoreet, sem nunc ultrices mauris, vitae fringilla leo ante eu lorem. Etiam consectetur massa at lorem maximus, luctus consectetur tortor ultrices. Vivamus ornare sapien sit amet mi faucibus, ac dictum eros pharetra. Morbi vitae orci mollis arcu fringilla laoreet sed ultricies augue. Donec cursus arcu sit amet nisi sollicitudin, quis consequat purus dapibus. Sed neque velit, tempus a cursus nec, dapibus a purus. Vivamus ut lacus finibus libero bibendum tincidunt vel non tellus. Praesent sit amet pellentesque felis. Praesent quis varius leo. Curabitur semper, ligula in ultricies porttitor, dolor lectus facilisis lectus, vitae mattis neque tellus vitae neque. Aenean nibh justo, convallis id ante feugiat, fermentum euismod ipsum.";

const MEDIUM_TEXT = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras et viverra arcu. Nam finibus nisi id lectus tempus semper. Curabitur tellus turpis, feugiat vel maximus id, pellentesque ac elit. Curabitur hendrerit vehicula sem a posuere. Integer egestas, velit nec consequat hendrerit, urna ante sodales erat, commodo aliquam ligula diam et neque. Nunc ut velit cursus, porta metus sit amet, interdum ipsum. Maecenas congue tortor diam, vitae aliquam elit faucibus at. Cras non pretium nibh, eu molestie nisl. Nulla et placerat purus, sit amet molestie neque. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Integer ullamcorper enim eget enim tristique, id tristique orci faucibus. Curabitur neque massa, ultricies quis neque eget, bibendum lobortis lectus.\n" +
    "\n" +
    "Vestibulum aliquet ipsum non blandit mattis. Curabitur commodo tincidunt risus, sit amet vehicula enim tincidunt a. Praesent facilisis turpis lectus, non consectetur ipsum consectetur dapibus. Aliquam ac ultricies purus. Nam malesuada cursus nibh, quis posuere metus cursus id. Integer dolor eros, euismod non nisi eget, congue pharetra mi. Aliquam convallis elit dolor, in scelerisque purus feugiat sit amet. Fusce euismod, enim at dignissim mollis, ipsum eros tincidunt tortor, ut condimentum turpis magna vitae sem. Etiam faucibus leo rutrum ligula varius efficitur. Etiam rhoncus nunc a arcu cursus malesuada. Curabitur aliquam lacus quis pulvinar dapibus. Maecenas tempus neque nec dolor tristique iaculis.";

const SHORT_TEXT = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras et viverra arcu. Nam finibus nisi id lectus tempus semper. Curabitur tellus turpis, feugiat vel maximus id, pellentesque ac elit. Curabitur hendrerit vehicula sem a posuere. Integer egestas, velit nec consequat hendrerit, urna ante sodales erat, commodo aliquam ligula diam et neque. Nunc ut velit cursus, porta metus sit amet, interdum ipsum. Maecenas congue tortor diam, vitae aliquam elit faucibus at. Cras non pretium nibh, eu molestie nisl. Nulla et placerat purus, sit amet molestie neque. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Integer ullamcorper enim eget enim tristique, id tristique orci faucibus. Curabitur neque massa, ultricies quis neque eget, bibendum lobortis lectus.";

const DEFAULT_TITLE = "Lorem ipsum dolor sit amet"

const DEFAULT_OPTION = {
    title: DEFAULT_TITLE,
    text: SHORT_TEXT
}

export {LONG_TEXT, MEDIUM_TEXT, SHORT_TEXT, DEFAULT_TITLE,DEFAULT_OPTION};